language: objective-c
osx_image: xcode6.4

before_install:
  - gem install --no-ri --no-rdoc cocoapods xcpretty

script:
  - set -o pipefail; xcodebuild -workspace *.xcworkspace -scheme "Hamcrest OSX" build test | xcpretty -c
  - set -o pipefail; xcodebuild -workspace *.xcworkspace -scheme "Hamcrest iOS" build test | xcpretty -c
  - pod lib lint

notifications:
  email: false
